excerpt_separator: "<!--more-->"
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
highlighter: rouge
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "autolink", "tables", "strikethrough"]
